language: java
jdk:
  - oraclejdk8
script: 
  - ant build 

after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN="5cb96507-96ce-496c-a034-6a9383db4a84"


[![codecov](https://codecov.io/gh/mihirm05/AST-WS2018/branch/master/graph/badge.svg)](https://codecov.io/gh/mihirm05/AST-WS2018)

