language: java
jdk:
  - oraclejdk8
script: 
  - ant build 

after_success:
  - bash <(curl -s https://codecov.io/bash)
 [![Code Coverage](https://img.shields.io/codecov/c/github/pvorb/property-providers/develop.svg)](https://codecov.io/github/pvorb/property-providers?branch=develop)

